name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/api/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install dependencies
      working-directory: ./api
      run: go mod tidy
    - name: Build
      working-directory: ./api
      run: go build -o main .
    - name: Run tests
      working-directory: ./api
      run: go test ./...
    - name: Build Docker image
      working-directory: ./api
      run: docker build -t goAPIProject:latest .
